### ISSUE TITLE
PyPI 源加速问题

### ISSUE THREAD

**Issue by LeoLRH** [iOSDevLog/slmethod#1]
#### 问题描述
用pip无法进行安装

**Comment by LeoLRH** [comment]
![image](https://user-images.githubusercontent.com/38356920/59235183-a2d2a000-8c22-11e9-815f-671523b582b4.png)

**Comment by jiaxianhua** [comment]
使用 pip3 替换 pip 试试

**Comment by LeoLRH** [comment]
效果是一样的




------------------ 原始邮件 ------------------
发件人: "jiaxianhua"<notifications@github.com>;
发送时间: 2019年6月11日(星期二) 上午8:42
收件人: "iOSDevLog/slmethod"<slmethod@noreply.github.com>;
抄送: "3336987685"<3336987685@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [iOSDevLog/slmethod] PyPI 源加速问题 (#1)




使用 pip3 替换 pip 试试

**Comment by jiaxianhua** [comment]
windows 下我没测试过，等会我用 windows 测试一下

**Comment by LeoLRH** [comment]
对的我的电脑系统就是windows10
谢谢您及时反馈麻烦了


------------------ 原始邮件 ------------------
发件人: "jiaxianhua"<notifications@github.com>;
发送时间: 2019年6月11日(星期二) 上午8:48
收件人: "iOSDevLog/slmethod"<slmethod@noreply.github.com>;
抄送: "3336987685"<3336987685@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [iOSDevLog/slmethod] PyPI 源加速问题 (#1)




windows 下我没测试过，等会我用 windows 测试一下

**Comment by jiaxianhua** [comment]
更新到 v0.2.2，我在 windows 7 下用 `pip install slmethod` 安装成功了，镜像加速一直没有更新。

![slmethod](https://user-images.githubusercontent.com/315101/59241302-b3dadb80-8c39-11e9-9255-1435ca6c7763.png)
![KMeans](https://user-images.githubusercontent.com/315101/59241306-b76e6280-8c39-11e9-83de-085b0f52f047.png)

**Comment by LeoLRH** [comment]
谢谢您，我的也可以了，刚才的问题解决方案，重新下载好升级pip，重启cmd，再次下载就好了




------------------ 原始邮件 ------------------
发件人: "jiaxianhua"<notifications@github.com>;
发送时间: 2019年6月11日(星期二) 中午11:12
收件人: "iOSDevLog/slmethod"<slmethod@noreply.github.com>;
抄送: "3336987685"<3336987685@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [iOSDevLog/slmethod] PyPI 源加速问题 (#1)




我在 windows 7 下用 pip install slmethod 安装成功了，镜像加速一直没有更新。
